repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-ast
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
#      language_version: python3.6
